name: pharmacy_mobile
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  adaptive_theme: ^3.1.1
  animated_flip_counter: ^0.2.5
  animated_text_kit: ^4.2.2
  animations: ^2.0.7
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  camera: ^0.10.0+4
  cnav: ^1.0.3
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  dio: ^4.0.6
  draggable_home: ^1.0.4
  drop_down_list: ^0.0.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.0.8
  flutter_neumorphic: ^3.2.0
  flutter_screenutil: ^5.6.0
  flutter_scroll_to_top: ^2.3.0
  flutter_slider_drawer: ^2.1.2
  font_awesome_flutter: ^10.3.0
  get: ^4.6.5
  get_storage: ^2.0.3
  glass: ^1.0.1+1
  google_fonts: ^3.0.1
  implicitly_animated_list: ^2.1.1
  intl: ^0.17.0
  introduction_screen: ^3.1.1
  loading_animation_widget: ^1.2.0+3
  lottie: ^2.0.0
  qr_code_scanner: ^1.0.1
  shimmer: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Nexa
      fonts:
        - asset: assets/fonts/nexa/Nexa-Trial-Regular.ttf
        - asset: assets/fonts/nexa/Nexa-Trial-Light.ttf
          weight: 100
        - asset: assets/fonts/nexa/Nexa-Trial-Book.ttf
          weight: 200
        - asset: assets/fonts/nexa/Nexa-Trial-Regular.ttf
          weight: 300
        - asset: assets/fonts/nexa/Nexa-Trial-Heavy.ttf
          weight: 400
        - asset: assets/fonts/nexa/Nexa-Trial-Bold.ttf
          weight: 900
        - asset: assets/fonts/nexa/Nexa-Trial-LightItalic.ttf
          style: italic
