name: pharmacy_mobile
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0-374.1.beta <3.0.0"

dependencies:
  adaptive_theme: ^3.1.1
  animations: ^2.0.7
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  camera: ^0.10.0+4
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_neumorphic: ^3.2.0
  flutter_screenutil: ^5.6.0
  font_awesome_flutter: ^10.3.0
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  introduction_screen: ^3.1.1
  lottie: ^2.0.0
  persistent_bottom_nav_bar: ^5.0.2
  qr_code_scanner: ^1.0.1
  shimmer: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Nexa
      fonts:
        - asset: assets/fonts/nexa/Nexa-Trial-Regular.ttf
        - asset: assets/fonts/nexa/Nexa-Trial-Light.ttf
          weight: 100
        - asset: assets/fonts/nexa/Nexa-Trial-Book.ttf
          weight: 200
        - asset: assets/fonts/nexa/Nexa-Trial-Regular.ttf
          weight: 300
        - asset: assets/fonts/nexa/Nexa-Trial-Heavy.ttf
          weight: 400
        - asset: assets/fonts/nexa/Nexa-Trial-Bold.ttf
          weight: 900
        - asset: assets/fonts/nexa/Nexa-Trial-LightItalic.ttf
          style: italic
