name: pharmacy_mobile
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  adaptive_theme: ^3.1.1
  android_alarm_manager_plus: ^2.1.1
  animated_digit: ^3.2.1
  animated_flip_counter: ^0.2.5
  animated_text_kit: ^4.2.2
  animations: ^2.0.7
  auto_animated_list: ^1.0.4
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  camera: ^0.10.0+4
  cloud_firestore: ^4.3.2
  cnav: ^1.0.3
  crypto: ^3.0.2
  cupertino_icons: ^1.0.2
  day_night_time_picker: ^1.1.5
  day_picker: ^2.1.1
  device_info_plus: ^8.1.0
  device_preview: ^1.1.0
  dio: ^5.0.1
  dio_cache_interceptor: ^3.4.0
  dio_cache_interceptor_hive_store: ^3.2.1
  draggable_home: ^1.0.4
  drop_down_list: ^0.0.4
  dropdown_button2: ^1.9.2
  easy_stepper: ^0.4.0
  equatable: ^2.0.5
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_ui_firestore: ^1.2.4
  flex_color_scheme: ^6.1.2
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^13.0.0
  flutter_native_timezone: ^2.0.0
  flutter_neumorphic: ^3.2.0
  flutter_screenutil: ^5.6.0
  flutter_scroll_to_top: ^2.3.0
  flutter_slidable: ^2.0.0
  flutter_slider_drawer: ^2.1.2
  font_awesome_flutter: ^10.3.0
  gallery_image_viewer: ^1.2.0
  get: ^4.6.5
  get_storage: ^2.0.3
  glass: ^1.0.1+1
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.2.3
  gradient_widgets: ^0.6.0
  horizontal_card_pager: ^1.1.1
  image_picker: ^0.8.7+1
  implicitly_animated_list: ^2.1.1
  intl: ^0.17.0
  introduction_screen: ^3.1.1
  jwt_decoder: ^2.0.1
  loading_animation_widget: ^1.2.0+4
  lottie: ^2.2.0
  motion: ^1.3.3
  network_info_plus: ^3.0.2
  permission_handler: ^10.2.0
  photo_view: ^0.14.0
  progressive_time_picker: ^0.0.7
  qr_code_scanner: ^1.0.1
  shimmer: ^2.0.0
  syncfusion_flutter_barcodes: ^21.1.38
  timeago: ^3.3.0
  timezone: ^0.9.1
  toggle_switch: ^2.0.1
  url_launcher: ^6.1.10
  webview_flutter: ^4.0.4

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - dotenv

  fonts:
    - family: Nexa
      fonts:
        - asset: assets/fonts/nexa/Nexa-Trial-Regular.ttf
        - asset: assets/fonts/nexa/Nexa-Trial-Light.ttf
          weight: 100
        - asset: assets/fonts/nexa/Nexa-Trial-Book.ttf
          weight: 200
        - asset: assets/fonts/nexa/Nexa-Trial-Regular.ttf
          weight: 300
        - asset: assets/fonts/nexa/Nexa-Trial-Heavy.ttf
          weight: 400
        - asset: assets/fonts/nexa/Nexa-Trial-Bold.ttf
          weight: 900
        - asset: assets/fonts/nexa/Nexa-Trial-LightItalic.ttf
          style: italic
